export let trans = {
	"Leak  test":	"测漏",
	"Flush rinse":	"冲洗",
	"Wash":			"酶洗",
	"Post rinse":	"漂洗",
	"Final rinse":	"终末漂洗",
	"Disinfection":	"消毒",
	"Vent":			"排气",
	"Detergent contact time":	"清洁剂接触时间",
	"Rinse contact time":	"漂洗接触时间",
	"Disinfectant contact time":	"消毒剂接触时间",
	"Basin temperature":	"清洗槽温度",
	"Alcohol delivered":	"酒精吹入",
	"No pressure water channel":	"水腔道无压力",
	"No pressure jet channel":	"水气腔道无压力",
	"No pressure air channel":	"空气腔道无压力",
	"No pressure extra channel":	"extra腔道无压力",
	"No pressure biopsy channel":	"活检腔道无压力",
	"No pressure suction channel":	"吸引腔道无压力",
	"No pressure elevator channel":	"附送水腔道无压力",
	"Biopsy channel disconnected":	"活检腔道未连接",
	"Block not pressurized or not connected":	"堵塞无增压或无连接",
	"Minor endoscope leak, cycle continuing safely":	"内镜轻微漏气,循环继续平稳进行",
	"Water inlet flow too low":	"入口水流过低",
	"No alcohol flow":	"无酒精流",
	"No flow air channel": "空气通道无流",
	"Manual control active":	"手动控制激活",
	"Stopped by operator": "被操作者停止",
	"Elevator channel disconnected": "附送水腔道未连接"
};
